# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shroudenv < Formula
  desc "Manage and protect environment variables cleanly"
  homepage "https://github.com/gitvadim/shroudenv"
  version "1.0.2-test2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitvadim/shroudenv/releases/download/v1.0.2-test2/shroudenv_1.0.2-test2_darwin_amd64.tar.gz"
      sha256 "8b65132e0a9dc56044b341f87dc6996d6d2f12c7c4c8e6cd49e8a1a7a4445ef9"

      define_method(:install) do
        bin.install "shroudenv"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitvadim/shroudenv/releases/download/v1.0.2-test2/shroudenv_1.0.2-test2_darwin_arm64.tar.gz"
      sha256 "14d3709f26088ecce5ece9e1dc0ca7b4e945c619e2eca6c40408f800ffc47a9a"

      define_method(:install) do
        bin.install "shroudenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitvadim/shroudenv/releases/download/v1.0.2-test2/shroudenv_1.0.2-test2_linux_amd64.tar.gz"
      sha256 "0e0986c3dbc2bfa10b7a5141d6edfd2d7da40ed7a0b253abcf04ed5b7d87813e"
      define_method(:install) do
        bin.install "shroudenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitvadim/shroudenv/releases/download/v1.0.2-test2/shroudenv_1.0.2-test2_linux_arm64.tar.gz"
      sha256 "0ba0b9adae90aabd45a53de0a8a8121a2dd8573e4607e6f83397e815b56416ab"
      define_method(:install) do
        bin.install "shroudenv"
      end
    end
  end
end
